import Head from "next/head";
import { motion as m } from "framer-motion";
import { container, item } from "../animation";

export default function Home() {
  return (
    <m.div
      initial={{ y: "100%" }}
      animate={{ y: "0%" }}
      transition={{ duration: 0.75, ease: "easeOut" }}
      exit={{ opacity: 1 }}
      className=" text-gray-900 absolute top-0 left-0 w-full h-full bg-gradient-to-t from-orange-100 to-gray-200 lg:px-48 px-16 "
    >
      <Head>
        <title>KimJisoo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="my-96 p-1 ">
          <h1 className="text-6xl text-center lg:text-right lg:text-9xl h-0">
            Kim Jisoo
          </h1>
        </div>
        <div className="flex justify-between">
          <div>
            <h2>Web Developer</h2>
            <h2>Freelancer</h2>
            <h2>2022</h2>
          </div>
          <m.div
            className="overflow-hidden"
            variants={container}
            initial="hidden"
            animate="show"
          >
            <m.h3 variants={item}>Creating the best products for you</m.h3>
            <m.h3 variants={item}>Web designs that make you happy</m.h3>
            <m.h3 variants={item}>Click contact for more</m.h3>
          </m.div>
        </div>
      </main>
    </m.div>
  );
}
