import Head from "next/head";
import { motion as m } from "framer-motion";

export default function Home() {
  return (
    <div>
      <Head>
        <title>PageT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="m-96 p-1 ">
          <h1 className="text-6xl text-center lg:text-right lg:text-9xl">
            Happy Pickle
          </h1>
        </div>
        <div className="flex justify-between">
          <div>
            <h2>Design</h2>
            <h2>Company</h2>
            <h2>2022</h2>
          </div>
          <div>
            <h3>This pickle gonna make you smile</h3>
            <h3>Scottish designs to make you happy</h3>
            <h3>Click contact for cool transitions</h3>
          </div>
        </div>
      </main>
    </div>
  );
}
